export enum AuthorizationActionTypes {
  FETCH_LOGIN = "FETCH_AUTHORIZATION",
  FETCH_REGISTRATION = "FETCH_REGISTRATION",
  FETCH_AUTHORIZATION_SUCCESS = "FETCH_AUTHORIZATION__SUCCESS",
  FETCH_AUTHORIZATION_ERROR = "FETCH_AUTHORIZATION_ERROR",
  FETCH_REFRESH = "FETCH_REFRESH",
  LOGOUT = "LOGOUT",
}
